# Site
name: "devgrow"
title: "devgrow"
description: "Increasing the performance & happiness of software engineering teams"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/fav.svg'
baseurl: ''
google_analytics: 'UA-151653454-1'
disqus: 'devgrow-1'
mailchimp-list: 'https://gmail.us5.list-manage.com/subscribe/post?u=922c89530ad76eefc90b8c22c&amp;id=359b869243'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  matt:
    name: Matt
    display_name: Matt Healy
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: team+matt@devgrow.net
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  ryan:
    name: Ryan
    display_name: Ryan DaRin    
    gravatar: 7eb20e38bbc7127401032569901912d6
    email: team+ryan@devgrow.net
    web: https://devgrow.net
    twitter: https://twitter.com/devgrow
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."



# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
